# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
strategyType:
enableSelector:
deploymentApiVersion: apps/v1
monitoring:
  name: Monitor
  image:
    repository: gitlab.iotcrawler.net:4567/monitoring/fault_detection/master
    tag: latest
    pullPolicy: IfNotPresent
    secrets:
    - name: gitlab-docker-registry
  service:
    enabled: true
    annotations: {}
    name: monitoring
    type: ClusterIP
    additionalHosts:
    commonName:
    externalPort: 8082
    internalPort: 8082
    production:
      url: parking.monitoring.iotcrawler.eu
      url_mdr: mdr.iotcrawler.eu
      port_mdr: 9090
      ngsi_address: http://parking.monitoring.iotcrawler.eu
      url_vs_creator: http://vs-creator.iotcrawler.eu
    staging:
      url: staging.parking.monitoring.iotcrawler.eu
      url_mdr: staging.mdr.iotcrawler.eu
      port_mdr: 9090
      ngsi_address: http://staging.parking.monitoring.iotcrawler.eu
      url_vs_creator: http://staging.vs-creator.iotcrawler.eu
  configmap: true
podAnnotations: {}
application:
  track: latest
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
gitlab:
  app:
  env:
  envName:
  envURL:
ingress:
  enabled: false
  url:
  tls:
    enabled: true
    secretName: ""
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  modSecurity:
    enabled: false
    secRuleEngine: "DetectionOnly"
    # secRules:
    #   - variable: ""
    #     operator: ""
    #     action: ""
prometheus:
  metrics: false
    #   matchLabels:
    #     stack: gitlab (This is an example. The labels should match the labels on the CloudSQLInstanceClass)
livenessProbe:
  path: "/monitoring/status"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/monitoring/status"
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
  probeType: "httpGet"

resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
  requests:
#    cpu: 100m
#    memory: 128Mi

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1

## Configure NetworkPolicy
## ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
#
networkPolicy:
  enabled: false
  spec:
    podSelector:
      matchLabels: {}
    ingress:
    - from:
      - podSelector:
          matchLabels: {}
      - namespaceSelector:
          matchLabels:
            app.gitlab.com/managed_by: gitlab

workers: {}
  # worker:
  #   replicaCount: 1
  #   terminationGracePeriodSeconds: 60
  #   command:
  #   - /bin/herokuish
  #   - procfile
  #   - start
  #   - worker
  #   preStopCommand:
  #   - /bin/herokuish
  #   - procfile
  #   - start
  #   - stop_worker
