apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{.Release.Name}}-monitoring
data:
  NGSI_ADDRESS: {{ if eq .Release.Name "staging" }} "{{ .Values.monitoring.service.staging.ngsi_address }}" {{ else }} "{{ .Values.monitoring.service.production.ngsi_address }}" {{ end }}
  FD_HOST: "0.0.0.0"
  # FD_HOST: {{ if eq .Release.Name "staging" }} "{{ .Values.monitoring.service.staging.url }}" {{ else }} "{{ .Values.monitoring.service.production.url }}" {{ end }}
  FD_PORT: "{{ .Values.monitoring.service.internalPort }}"
  FD_CALLBACK: "http://{{ if eq .Release.Name "staging" }} {{ .Values.monitoring.service.staging.url }} {{ else }} {{ .Values.monitoring.service.production.url }} {{ end }}/faultdetection/callback"
  VS_CREATER_ADDRESS: {{ if eq .Release.Name "staging" }} "{{ .Values.monitoring.service.staging.url_vs_creator }}" {{ else }} "{{ .Values.monitoring.service.production.url_vs_creator }}" {{ end }}
  #RECOVERY_METHOD: "MCMC"
  RECOVERY_METHOD: "BME"
